language: php

php: [7.1.19, 7.2]

install:
  - composer install

script:
    - php vendor/bin/phpcs --standard=PSR1 ./src --ignore=*/spec/*
    - php vendor/bin/phpcs --standard=PSR2 ./src --ignore=*/spec/*
    - php vendor/bin/phpstan analyse ./src --level max
